[package]
name = "quefi"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.5", features = ["json", "blocking"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
ratatui = "0.27.0"
tui-textarea = "0.5.1"
rodio = "0.19.0"
regex = "1.10.5"
