[package]
name = "quefi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
tokio = { version = "1.38.0", features = ["io-util", "fs", "macros", "rt-multi-thread", "process", "time"] }
ratatui = "0.27.0"
tui-textarea = "0.5.1"
